### PR TITLE
Updates react peer to include 16+17+18

### PR DESCRIPTION
**Pull request by CaptainN**
This PR does nothing other than increment peerDeps to include react 18 - nothing at all, except that.

I also took a quick look through the code, and didn't find any red flags for support in React 18 - it should work wonderfully.

### CODE REVIEW

**Comment by qb3l-pplsi** [comment]
Let's merge this please. Peer dependencies broken on other stuff because of this

**Comment by milton-producercloud** [comment]
This has to be merged, currently the library cannot be used with React 18

**Review by milton-producercloud — APPROVED** [review]

**Comment by yumemi-omi** [comment]
@nygardk

**Comment by TomasCarlson** [comment]
@nygardk any update with this? Causing some issues with builds and would love a non-hacky solution

**Comment by Carlos-Carsdfj** [comment]
Please merge this to use react 18

**Comment by yumemi-omi** [comment]
@nygardk 
Please check.

**Comment by ayrosochang** [comment]
@nygardk 
Please check this

**Comment by nygardk** [comment]
Has been fixed in [v4.4.1](https://github.com/nygardk/react-share/releases/tag/v4.4.1).

**Pull request closed without merging**
