### PR TITLE
react-share 3.0.0

### PR DESCRIPTION
**Pull request by aautio**
Here is a pull request from `v3` branch containing all pending changes. Updated `CHANGELOG.md` and `README.md` are included.

* A default `aria-label` is generated for the share buttons. It is based on the network name. Use `additionalProps` to override.
* Removed support for Google+.
* Removed support for `<LinkedInShareCount/>`. LinkedIn no longer provides an API to fetch share counts.
* Removed `title` and `description` from `<LinkedInShareButtons/>`.
* Fix: `<EmailShareButton/>` includes `body` before `url`.
* Fix: `<EmailShareButton/>` and `<ViberShareButton/>` allow customization of `separator`.
* Thanks @finppp, @madkoding and @andrewl913!

Sorry it took so long to prepare this - but better late than never I guess. @nygardk would you review this, merge and publish to NPM if all looks good? A correct date should be set to `CHANGELOG.md` line 3: `## 3.0.0 (Feb ?, 2018)` while merging.

I should have time to do fixes/changes within the upcoming week if any are required.

### CODE REVIEW

**Comment by aautio** [comment]
Everything sounds great!

`centerWindowOnScreen` might require testing with single and dual monitor -setups to get it working in a consistent manner?

---

I like the `Javascript -> Implicit Project Config: Check JS` -feature of Visual Studio Code to run TypeScript checks for plain `.js`-files. It has been a huge help with JS projects. 

The implicit check works just great for most NPM packages - but not yet with `react-share` when I'm importing things this way:

```
import WhatsappShareButton from 'react-share/lib/WhatsappShareButton'
```

I could pitch in to the TypeScript-conversion with ☝️in my mind.

**Comment by aautio** [comment]
Merged Instapaper and Pocket sharing to `v3` branch via #201

**Comment by andrewl913** [comment]
late reply, but awesome!

**Comment by aautio** [comment]
@nygardk I've updated the changelog and merged everything to the branch `v3`. The actual release date needs to be added there - otherwise everything should be listed.

Would you mind building and publishing a `3.0.0-beta.0` from `v3` to npm?

**Comment by nygardk** [comment]
This is now published as `3.0.0-beta.0` in npm. Installable with `npm i react-share@beta`.

**Comment by aautio** [comment]
> @aautio This is now published as `3.0.0-beta.0` in NPM. Installable with `npm i react-share@beta`.

Nice! I'll test it next week within a few sites and get back to you.

**Comment by nygardk** [comment]
> > @aautio This is now published as `3.0.0-beta.0` in NPM. Installable with `npm i react-share@beta`.
> 
> Nice! I'll test it next week within a few sites and get back to you.

Any update on testing 🙂?

**Comment by aautio** [comment]
Hi @nygardk, sorry for dropping the ball. I've left the country for a few weeks without my laptop. I'll be back around 2nd or 3rd of May. Would you be ok with waiting that far?

**Comment by nygardk** [comment]
@aautio 
Hey, of course, it's ok :). Have fun abroad!

**Comment by aautio** [comment]
@nygardk - sorry the delay. But I've finally had the chance to test the v3 `beta`.

Short summary: It just works 👍

Should we go forward and remove the beta label, merge this pr and publish a `3.0.0` version to NPM?

**Comment by nygardk** [comment]
Published!

**Pull request merged**
