### PR TITLE
Add support for Facebook Messenger share button

### PR DESCRIPTION
**Pull request by jmfsilva**
The other PR has to many changes on files that are not required.
Added also some more options to customize popup window.

Documentation for Facebook messenger: https://developers.facebook.com/docs/sharing/reference/send-dialog/#params

### CODE REVIEW

**Comment by me4502** [comment]
Is there any update on this PR?

**Comment by robinsingh-bw** [comment]
Any plans to merge this?

**Comment by nygardk** [comment]
Sorry everyone, I've failed to find the time for the maintenance lately. It's in my interests to do it soon!

**Comment by nygardk** [comment]
Thank you for your contribution! This feature has been implemented in `v4.0.0`.

**Pull request closed without merging**
