### PR TITLE
add sharing attributes to twitter and pinterest

### PR DESCRIPTION
**Pull request by jmathews**
Passed along `via` and `hashtags` attributes to twitter sharing; added `description` attribute to pinterest sharing.

### CODE REVIEW

**Comment by nygardk** [comment]
Hi! Seems good. Additionally, could add some documentation to the readme regarding the additions? I'm not sure if the readme structure is good at all, so feel free to make changes if you wish.

**Comment by jmathews** [comment]
Excellent!  Will do.

Also how do you feel about adding an option onShare callback attribute to
the share link components?  This would allow someone to track shares
through Google Analytics or their own tracking system.  If that sounds
interesting, I can put those changes in another commit (same PR or
different?).

BTW, I'm slammed with work for the next few days so may not get to this
until later in the week.

Best,
Jeff

On Sun, Apr 17, 2016 at 9:58 PM, Klaus Nygård <notifications@github.com>
wrote:

> Hi! Seems good. Additionally, could add some documentation to the readme
> regarding the additions? I'm not sure if the readme structure is good at
> all, so feel free to make changes if you wish.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nygardk/react-share/pull/7#issuecomment-211200368>
>



-- 
Jeffrey Mathews
jeffreymathews@gmail.com
+1 410-336-2279

**Comment by nygardk** [comment]
Awesome!

OnShare callback sounds like a good feature. Feel free to commit those improvements as well!

**Comment by jmathews** [comment]
Hey Klaus ... sorry I haven't forgotten about this, but have been traveling
with bad internet.  I'll work on it this weekend!  Jeff

On Tue, Apr 19, 2016 at 1:15 AM, Klaus Nygård <notifications@github.com>
wrote:

> Awesome!
>
> OnShare callback sounds like a good feature. Feel free to commit those
> improvements as well!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nygardk/react-share/pull/7#issuecomment-211767225>
>



-- 
Jeffrey Mathews
jeffreymathews@gmail.com
+1 410-336-2279

**Pull request merged**
