### PR TITLE
Fixed a problem that Twitter share button doesn't work on Android OS

### LINKED ISSUE #484: Twitter share button doesn't work on Android 12
# Problem

I put this button on my web site, and pushed it on Android 12.
Twitter application opened automatically, but the following message was shown.
> The term you entered did not bring up any results. Please try again later.

# Cause
The url of TwitterShareButton
https://github.com/nygardk/react-share/blob/454860844d11d11d23112db1982feaf0ef4f1f09/src/TwitterShareButton.ts
```
    'https://twitter.com/share' +
```

According to the Twitter help page, the correct share url is `https://twitter.com/intent/tweet` . 

[Twitter help page] How to add the Tweet button to your website
https://help.twitter.com/en/using-twitter/add-twitter-share-button

Make a share button with the explained way. The url path of the share button is `https://twitter.com/intent/tweet? ...` .

When we access `https://twitter.com/share`, then it automatically redirect to  `https://twitter.com/intent/tweet` normally.  However, this doesn't work on Android OS.

### PR DESCRIPTION
**Pull request by sakabar**
Fixed #484

### CODE REVIEW

**Comment by piro0919** [comment]
@nygardk 

I would like you to check this PR. 🙇

**Comment by freecates** [comment]
Is this PR going to be merged anytime soon?
Thanks.

**Comment by SgtTepper** [comment]
@nygardk can you please approve?

**Comment by rafaolivares** [comment]
Is this PR going to be merged anytime soon?
Thanks.

**Comment by uedayuji** [comment]
@nygardk could you please approve?

**Comment by Ciaran0** [comment]
It would be great to have this merged.

**Comment by rhtaylor** [comment]
Does this work?

**Comment by SSRamiSanta** [comment]
@nygardk could you please merge?

**Review by szabodavid99 — APPROVED** [review]

**Review by adeherysh — APPROVED** [review]

**Comment by nygardk** [comment]
Hey and thanks for the contribution! This has included in version `5.0.2`.

**Pull request closed without merging**
