### PR TITLE
Twitter X Logo Added

### PR DESCRIPTION
**Pull request by ashikp**

### CODE REVIEW

**Comment by ashikp** [comment]
No. Only admin can. But i found other way to work on it

**Comment by TimBenjamin** [comment]
What was your other way, out of interest? It seems the project owner has gone missing :-(

**Comment by ashikp** [comment]
<TwitterShareButton url={url}>
                    <svg viewBox="0 0 64 64" width="40" height="40" fill="#ffffff">
                        <circle cx={32} cy={32} r={31} fill="#0B2972" />
                        <path
                            d="M 41.116 18.375 h 4.962 l -10.8405 12.39 l 12.753 16.86 H 38.005 l -7.821 -10.2255 L 21.235 47.625 H 16.27 l 11.595 -13.2525 L 15.631 18.375 H 25.87 l 7.0695 9.3465 z m -1.7415 26.28 h 2.7495 L 24.376 21.189 H 21.4255 z"
                            fill="white"
                        ></path>
                    </svg>
                </TwitterShareButton>
                
                do something like this

**Comment by TimBenjamin** [comment]
Oh awesome, thanks very much, that makes life easier :-)

**Comment by ying-ying-wu** [comment]
We just happened to use the font awesome library so we just used that instead (had to update the brand collection to v6 to get the new X icons).

**Comment by nygardk** [comment]
Thanks, `XIcon` has been added in v5.

**Pull request closed without merging**
