### PR TITLE
Providing ES modules with ES5, updated tooling, includes API changes

### PR DESCRIPTION
**Pull request by aautio**
Here is a quite large pull request. I'll try to fill you in what is included.

Chore: Tooling upgrades
 - Webpack upgraded
 - Babel upgraded
 - ESLint upgraded
 - react-hot-loader upgraded

Enabling tiny bundle sizes with ES modules:
 - package.json contains `module` definition
 - build generates ES modules
 - source code has been split to small files to allow picky imports
 - includes API changes

With these changes you would be able to imports just small pieces of the `react-share` without the burden of the whole library. 

For example this would be possible and would yield just a small increase to your app bundle and dismiss the dependencies to all other networks or the share count getters:

```
import FacebookShareButton from 'react-share/es/FacebookShareButton'
import FacebookIcon from 'react-share/es/FacebookIcon'
```

You are still able to import the stuff from root. But I would avoid it. It will yield larger bundles unless you have an aggressive tree-shaking & dead-code-elimination solution in place.

```
import { FacebookShareButton } from 'react-share'
import { FacebookIcon } from 'react-share'
```

CJS build is also still included and defined in the `main` of `package.json`  

This is my first look at ES modules etc. I might have taken wrong turns somewhere. Would something like this be good for `react-share`? I'd love to hear your thoughts on these kinds of changes. Is this something you might want to consider or could some other approach be better?

I have not yet made any edits to the readme, nor any upgrade instructions. But I can take a look at them if the change looks like something that might work.

### CODE REVIEW

**Comment by nygardk** [comment]
Thank you very much! Just quickly glancing it over, the refactoring and changes look very good to me.  I guess it will be time for v2.0 release. I'll do the actual review as soon as I have time! 

Did you, btw, verify that the new build(s) is(are) ok?

**Comment by aautio** [comment]
I verified the ES modules by setting up a local app with create-react-app. They worked. Also the Demo.jsx has been updated and it seemed to work. 

As for the CJS build I've read through the builded files and they _seem_ to be ok. But I've not tested them with any actual builds.

Perhaps these changes should be first published as a beta release? `react-share@next`? It would give us some room to test things out with different kinds of apps.

I hope to have time to update the readme on Thursday or on Friday. Also if you spot any problems, I'll be happy to fix & adjust.

**Comment by aautio** [comment]
Great! I tested the v2.0.0-beta.0 with a few sites that I'm involved with. The package seems to work ok.

It is now possible import just pieces of the library. No tree-shaking is required if you import individual files directly by doing something like this:

```
import FacebookShareButton from 'react-share/lib/FacebookShareButton'
import FacebookIcon from 'react-share/lib/FacebookIcon'
```

We are only using the share buttons & icons for a few social media networks and we are not using the share count getters at all. The example above uses CJS build, but the same results are to be expected with the ES modules version as well.

For us it seems that the our builds are now tens of kilobytes smaller than previously \o/

**Comment by nygardk** [comment]
Great to hear! I will make the actual `v2.0.0` sometime soon!

**Pull request merged**
