### PR TITLE
Update react peerDependencies to support React 18

### PR DESCRIPTION
**Pull request by alexdrimbe**

### CODE REVIEW

**Comment by kpman** [comment]
@nygardk Could you take a look for this PR?

**Comment by sukantamaikap** [comment]
It would be great to have support for react 18

**Review by rynocouse — APPROVED** [review]

**Comment by alexdrimbe** [comment]
@nygardk, the changes have been approved, can you merge it?

**Comment by skb1129** [comment]
@nygardk, can you please merge and release these changes?

**Comment by CaptainN** [comment]
This patch has a lot in it, besides just updating the peer deps. Would a simpler/cleaner PR have a greater chance of getting merged?

**Comment by CaptainN** [comment]
I made a super simple, one line PR #464

**Comment by nygardk** [comment]
Thanks. React 18 has been supported in `peerDeps` since version `4.4.1`.

**Pull request closed without merging**
